trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: BatchScript@1
  inputs:
    filename: 'power.bat'
    arguments: '3 4'
  displayName: power.bat  
- task: BatchScript@1
  inputs:
    filename: 'calc.bat'
    arguments: '4 2'
  displayName: calc.bat  